import type { ComponentType, SVGProps } from "react";

export type LucideSvgIcon = ComponentType<
  SVGProps<SVGSVGElement> & { size?: number | string; strokeWidth?: number | string }
>;

type IconLoader = () => Promise<{ default: LucideSvgIcon }>;

/** Loaders explícitos — um chunk por ícone, sem importar o mapa completo do Lucide */
export const AD_ICON_LOADERS: Record<string, IconLoader> = {
  apple: () => import("lucide-react/dist/esm/icons/apple.js"),
  armchair: () => import("lucide-react/dist/esm/icons/armchair.js"),
  baby: () => import("lucide-react/dist/esm/icons/baby.js"),
  backpack: () => import("lucide-react/dist/esm/icons/backpack.js"),
  bandage: () => import("lucide-react/dist/esm/icons/bandage.js"),
  bed: () => import("lucide-react/dist/esm/icons/bed.js"),
  beer: () => import("lucide-react/dist/esm/icons/beer.js"),
  bird: () => import("lucide-react/dist/esm/icons/bird.js"),
  bone: () => import("lucide-react/dist/esm/icons/bone.js"),
  "book-open": () => import("lucide-react/dist/esm/icons/book-open.js"),
  briefcase: () => import("lucide-react/dist/esm/icons/briefcase.js"),
  brush: () => import("lucide-react/dist/esm/icons/brush.js"),
  bug: () => import("lucide-react/dist/esm/icons/bug.js"),
  bus: () => import("lucide-react/dist/esm/icons/bus.js"),
  cake: () => import("lucide-react/dist/esm/icons/cake.js"),
  camera: () => import("lucide-react/dist/esm/icons/camera.js"),
  candy: () => import("lucide-react/dist/esm/icons/candy.js"),
  car: () => import("lucide-react/dist/esm/icons/car.js"),
  "car-front": () => import("lucide-react/dist/esm/icons/car-front.js"),
  cat: () => import("lucide-react/dist/esm/icons/cat.js"),
  cherry: () => import("lucide-react/dist/esm/icons/cherry.js"),
  "circle-dot": () => import("lucide-react/dist/esm/icons/circle-dot.js"),
  "clipboard-list": () => import("lucide-react/dist/esm/icons/clipboard-list.js"),
  coffee: () => import("lucide-react/dist/esm/icons/coffee.js"),
  "cup-soda": () => import("lucide-react/dist/esm/icons/cup-soda.js"),
  dog: () => import("lucide-react/dist/esm/icons/dog.js"),
  dumbbell: () => import("lucide-react/dist/esm/icons/dumbbell.js"),
  fish: () => import("lucide-react/dist/esm/icons/fish.js"),
  flame: () => import("lucide-react/dist/esm/icons/flame.js"),
  "flower-2": () => import("lucide-react/dist/esm/icons/flower-2.js"),
  footprints: () => import("lucide-react/dist/esm/icons/footprints.js"),
  fuel: () => import("lucide-react/dist/esm/icons/fuel.js"),
  "gamepad-2": () => import("lucide-react/dist/esm/icons/gamepad-2.js"),
  gem: () => import("lucide-react/dist/esm/icons/gem.js"),
  gift: () => import("lucide-react/dist/esm/icons/gift.js"),
  glasses: () => import("lucide-react/dist/esm/icons/glasses.js"),
  "graduation-cap": () => import("lucide-react/dist/esm/icons/graduation-cap.js"),
  guitar: () => import("lucide-react/dist/esm/icons/guitar.js"),
  hammer: () => import("lucide-react/dist/esm/icons/hammer.js"),
  handbag: () => import("lucide-react/dist/esm/icons/handbag.js"),
  "hand-heart": () => import("lucide-react/dist/esm/icons/hand-heart.js"),
  handshake: () => import("lucide-react/dist/esm/icons/handshake.js"),
  "hard-hat": () => import("lucide-react/dist/esm/icons/hard-hat.js"),
  headphones: () => import("lucide-react/dist/esm/icons/headphones.js"),
  heart: () => import("lucide-react/dist/esm/icons/heart.js"),
  "heart-handshake": () => import("lucide-react/dist/esm/icons/heart-handshake.js"),
  hospital: () => import("lucide-react/dist/esm/icons/hospital.js"),
  house: () => import("lucide-react/dist/esm/icons/house.js"),
  lamp: () => import("lucide-react/dist/esm/icons/lamp.js"),
  laptop: () => import("lucide-react/dist/esm/icons/laptop.js"),
  layers: () => import("lucide-react/dist/esm/icons/layers.js"),
  leaf: () => import("lucide-react/dist/esm/icons/leaf.js"),
  lightbulb: () => import("lucide-react/dist/esm/icons/lightbulb.js"),
  megaphone: () => import("lucide-react/dist/esm/icons/megaphone.js"),
  mic: () => import("lucide-react/dist/esm/icons/mic.js"),
  monitor: () => import("lucide-react/dist/esm/icons/monitor.js"),
  motorbike: () => import("lucide-react/dist/esm/icons/motorbike.js"),
  package: () => import("lucide-react/dist/esm/icons/package.js"),
  palette: () => import("lucide-react/dist/esm/icons/palette.js"),
  "paw-print": () => import("lucide-react/dist/esm/icons/paw-print.js"),
  pill: () => import("lucide-react/dist/esm/icons/pill.js"),
  pizza: () => import("lucide-react/dist/esm/icons/pizza.js"),
  plug: () => import("lucide-react/dist/esm/icons/plug.js"),
  printer: () => import("lucide-react/dist/esm/icons/printer.js"),
  puzzle: () => import("lucide-react/dist/esm/icons/puzzle.js"),
  rabbit: () => import("lucide-react/dist/esm/icons/rabbit.js"),
  ribbon: () => import("lucide-react/dist/esm/icons/ribbon.js"),
  salad: () => import("lucide-react/dist/esm/icons/salad.js"),
  scissors: () => import("lucide-react/dist/esm/icons/scissors.js"),
  shirt: () => import("lucide-react/dist/esm/icons/shirt.js"),
  "shopping-bag": () => import("lucide-react/dist/esm/icons/shopping-bag.js"),
  "shopping-basket": () => import("lucide-react/dist/esm/icons/shopping-basket.js"),
  "shower-head": () => import("lucide-react/dist/esm/icons/shower-head.js"),
  smartphone: () => import("lucide-react/dist/esm/icons/smartphone.js"),
  soup: () => import("lucide-react/dist/esm/icons/soup.js"),
  sparkles: () => import("lucide-react/dist/esm/icons/sparkles.js"),
  sprout: () => import("lucide-react/dist/esm/icons/sprout.js"),
  star: () => import("lucide-react/dist/esm/icons/star.js"),
  stethoscope: () => import("lucide-react/dist/esm/icons/stethoscope.js"),
  tag: () => import("lucide-react/dist/esm/icons/tag.js"),
  target: () => import("lucide-react/dist/esm/icons/target.js"),
  tent: () => import("lucide-react/dist/esm/icons/tent.js"),
  "tree-pine": () => import("lucide-react/dist/esm/icons/tree-pine.js"),
  truck: () => import("lucide-react/dist/esm/icons/truck.js"),
  turtle: () => import("lucide-react/dist/esm/icons/turtle.js"),
  tv: () => import("lucide-react/dist/esm/icons/tv.js"),
  umbrella: () => import("lucide-react/dist/esm/icons/umbrella.js"),
  users: () => import("lucide-react/dist/esm/icons/users.js"),
  "utensils-crossed": () => import("lucide-react/dist/esm/icons/utensils-crossed.js"),
  watch: () => import("lucide-react/dist/esm/icons/watch.js"),
  wheat: () => import("lucide-react/dist/esm/icons/wheat.js"),
  wrench: () => import("lucide-react/dist/esm/icons/wrench.js"),
};

export function loadAdIcon(lucideKey: string): IconLoader | undefined {
  return AD_ICON_LOADERS[lucideKey];
}
